apiVersion: v2
name: cert-manager-ca-issuer
home: https://blog.sandipb.net
description: A Helm chart for adding a CA issuer for cert-manager
type: application
version: 0.1.0
appVersion: "1.6.0"
maintainers:
  - name: Sandip Bhattacharya
    email: sandipb@showmethesource.org
