apiVersion: v1
metadata:
  name: {{ .Values.issuerSecretName }}
  namespace: {{ .Values.issuerNamespace }}
data:
  tls.crt: {{ index .Values.issuerTLSSecrets "tls.crt" }}
  tls.key: {{ index .Values.issuerTLSSecrets "tls.key" }}
kind: Secret
type: kubernetes.io/tls
