apiVersion: v1
metadata:
  name: {{ .Values.issuerSecretName }}
  namespace: {{ .Values.issuerNamespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  tls.crt: {{ index .Values.issuerTLSSecrets "tls.crt" }}
  tls.key: {{ index .Values.issuerTLSSecrets "tls.key" }}
kind: Secret
type: kubernetes.io/tls
