apiVersion: cert-manager.io/v1
kind: {{ .Values.issuerKind }}
metadata:
  name: {{ .Values.issuerName }}
{{- if (eq .Values.issuerKind "Issuer") }}
  namespace: {{ .Values.issuerNamespace }}
{{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ca:
    secretName: {{ .Values.issuerSecretName }}

